# This configuration is intended for production use and was created with respect to the security guide.
# The provided links to documentation guides for each property will give more information about the purpose of each property.
# security guide: https://docs.cibseven.org/manual/latest/user-guide/security/

camunda.bpm:
# https://docs.cibseven.org/manual/latest/user-guide/security/#http-header-security-in-webapps
# https://docs.cibseven.org/manual/latest/webapps/shared-options/header-security/
  webapp:
    csrf:
      enable-same-site-cookie: true
      same-site-cookie-option: STRICT
    header-security:
      hsts-disabled: false
      content-security-policy-value: base-uri 'self';
        default-src 'self' 'unsafe-inline' 'unsafe-eval';
        img-src 'self' data:;
        block-all-mixed-content;
        form-action 'self';
        frame-ancestors 'none';
        object-src 'none';
        sandbox
          allow-forms
          allow-scripts
          allow-same-origin
          allow-popups

# https://docs.cibseven.org/manual/latest/user-guide/security/#authorization
# https://docs.cibseven.org/manual/latest/user-guide/process-engine/authorization-service/
  authorization.enabled: true

  generic-properties.properties:
# https://docs.cibseven.org/manual/latest/user-guide/security/#variable-values-from-untrusted-sources
    deserialization-type-validation-enabled: true
    deserialization-allowed-packages:
    deserialization-allowed-classes:
# https://docs.cibseven.org/manual/latest/user-guide/security/#password-policy
# https://docs.cibseven.org/manual/latest/user-guide/process-engine/password-policy/
    enable-password-policy: true

  run:
# https://docs.cibseven.org/manual/latest/user-guide/security/#authentication
# https://docs.cibseven.org/manual/latest/user-guide/cibseven-run/#authentication
    auth.enabled: true

server:
# https://docs.cibseven.org/manual/latest/user-guide/cibseven-run/#https
# do not use the provided certificate in production
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: camunda
    key-store-type: pkcs12
    key-alias: camunda
    key-password: camunda
  port: 8443

# https://docs.cibseven.org/manual/latest/user-guide/security/#http-header-security-in-webapps
# https://docs.cibseven.org/manual/latest/webapps/shared-options/header-security/
  servlet.session.cookie:
    secure: true
    http-only: true

# https://docs.cibseven.org/manual/latest/user-guide/cibseven-run/#logging
# https://docs.cibseven.org/manual/latest/user-guide/logging/#process-engine
logging:
   level.root: INFO
   file: logs/camunda-bpm-run.log

# datasource configuration is required
# do not use the H2 databse in production
# https://docs.cibseven.org/manual/latest/user-guide/cibseven-run/#connect-to-a-database
# https://docs.cibseven.org/manual/latest/user-guide/cibseven-run/#database
spring.datasource:
  url: jdbc:h2:./camunda-h2-test-production/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password: sa

# CIB seven Keycloak Identity Provider Plugin
# Externalized Keycloak configuration
keycloak:
  # Keycloak access for the Identity Provider plugin.
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM:camunda}
  # Keycloak Camunda Identity Client
  client.id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET}

plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.host}/auth/realms/${keycloak.realm}
  keycloakAdminUrl: ${keycloak.host}/auth/admin/realms/${keycloak.realm}
  clientId: ${keycloak.client.id}
  clientSecret: ${keycloak.client.secret}
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true

spring:
  config:
    import:
      - optional:classpath:cibseven-webclient.properties

cibseven:
  webclient:
    engineRest:
      # Base URL of the CIB seven engine
      url: http://localhost:8080
      # Configurable REST API path (default: /engine-rest)
      path: /engine-rest
    historyLevel: full
    # Token generation
    authentication:
      jwtSecret:
      tokenValidMinutes: 60
      tokenProlongMinutes: 1440
    # LDAP
    ldap:
      url: ldap://ldap.cibseven.org
      folder: DC=cibseven,DC=org
      userNameAttribute: samAccountName
      userDisplayNameAttribute: name
      modifiedDateFormat: yyyyMMddHHmmss.SX
      followReferrals: follow

    # BPM Provider
    bpm:
      provider: org.cibseven.webapp.providers.SevenProvider
    # User providers
    user:
      provider: org.cibseven.webapp.auth.SevenUserProvider
      # provider: org.cibseven.webapp.auth.LdapUserProvider
      # provider: org.cibseven.webapp.auth.KeycloakUserProvider
      # provider: org.cibseven.webapp.auth.AdfsUserProvider

    # Set the wild card is gonna be used for the users search. By default is "*".
    users:
      search:
        wildcard:
     # If this params is set to false, the number of instances and incidents wont be taken.
    fetchInstances: true
    fetchIncidents: true
     # External token user creation
    token:
      secret: 
      deny:
        external:
          ip: true
    datasource:
      fileValue:
        enabled: false
    cockpit:
      url: /camunda/app/cockpit/default/
    theme: cib

    services:
      basePath: services/v1

    api:
      common:
        title: "CIB seven webclient API"
        description: "This API exposes the functionality of CIB seven webclient as a REST service under the Apache License 2.0."
        termsOfService: "https://www.apache.org/licenses/LICENSE-2.0"
        license: "Apache 2.0"
        licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0"
        contact:
          name: "CIB seven"
          url: "https://cibseven.org"
          email: "info@cibseven.org"
        # webclient server url for the swagger-ui. Only needs to be set if the automatic detection is wrong.
        url:
