spring.datasource:
  url: ${JDBC_URL:jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
  username: ${JDBC_USER:sa}
  password: ${JDBC_PASSWORD:sa}
#spring.h2.console.enabled: true

spring:
  jersey:
    application-path: /engine-rest
  config:
    import:
      - optional:classpath:cibseven-webclient.properties

camunda.bpm:
  history-level: audit
  authorization:
    enabled: true
  filter:
    create: All tasks
  oauth2:
    identity-provider:
      enabled: false

# Externalized Keycloak configuration
keycloak:
  # SSO Authentication requests. Send by application as redirect to the browser
  url.auth: ${KEYCLOAK_URL_AUTH:http://localhost:9000/auth}
  # SSO Token requests. Send from the application to Keycloak
  url.token: ${KEYCLOAK_URL_TOKEN:http://localhost:9000/auth}
  # Keycloak access for the Identity Provider plugin.
  url.plugin: ${KEYCLOAK_URL_PLUGIN:http://localhost:9000/auth}

  # Keycloak Camunda Identity Client
  client.id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET:0F0yFyCvv2T901fvMSbKlAd7f8QkyxNg}

cibseven:
  webclient:
    services.basePath: webapp/services/v1
    engineRest:
      url: http://localhost:8080
    authentication:
      tokenValidMinutes: 30
      tokenProlongMinutes: 10
    sso:
      active: true
      endpoints:
        authorization: ${keycloak.url.auth}/realms/camunda/protocol/openid-connect/auth
        token:  ${keycloak.url.auth}/realms/camunda/protocol/openid-connect/token
        jwks: ${keycloak.url.auth}/realms/camunda/protocol/openid-connect/certs
        user: ${keycloak.url.auth}/realms/camunda/protocol/openid-connect/users
      clientId: ${keycloak.client.id}
      clientSecret: ${keycloak.client.secret}
      scopes: openid email profile
      userIdProperty: preferred_username
      userNameProperty: name
      accessTokenToEngineRest: true
    bpm:
      provider: org.cibseven.webapp.providers.SevenProvider
    user:
      provider: org.cibseven.webapp.auth.KeycloakUserProvider

server:
  port: 8080

# Metrics & Health
management:
  endpoint.health.probes.enabled: true
  endpoints:
    web.exposure.include: env,health,info,metrics

# Spring Boot Security OAuth2 SSO
spring.security:
  oauth2:
    client:
      registration:
        keycloak:
          provider: keycloak
          client-id: ${keycloak.client.id}
          client-secret: ${keycloak.client.secret}
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope: openid, profile, email
      provider:
        keycloak:
          issuer-uri: ${keycloak.url.auth}/realms/camunda
          authorization-uri: ${keycloak.url.auth}/realms/camunda/protocol/openid-connect/auth
          user-info-uri: ${keycloak.url.auth}/realms/camunda/protocol/openid-connect/userinfo
          token-uri: ${keycloak.url.token}/realms/camunda/protocol/openid-connect/token
          jwk-set-uri: ${keycloak.url.token}/realms/camunda/protocol/openid-connect/certs
          # set user-name-attribute one of: 
          # - sub                -> default; using keycloak ID as camunda user ID
          # - email              -> useEmailAsCamundaUserId=true
          # - preferred_username -> useUsernameAsCamundaUserId=true
          user-name-attribute: preferred_username

logging.level.org.springframework.security: DEBUG

# CIB seven Rest API
rest.security:
  # CIB seven webapp supports communication with the secured engine REST ONLY from version 2.1.0 onward
  enabled: true
  provider: keycloak
  required-audience: camunda-rest-api

# CIB seven Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url.plugin}/realms/camunda
  keycloakAdminUrl: ${keycloak.url.plugin}/admin/realms/camunda
  clientId: ${keycloak.client.id}
  clientSecret: ${keycloak.client.secret}
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  enforceSubgroupsInGroupQuery: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true